import fs from "fs";
import { thinkShoppingPlan } from "./ai.js";
import { askPaidInfoShop } from "./mpp-client.js";
import { sendTempoPayment } from "./tempo.js";

const LOG_FILE = "./secret-log.json";

function readLog() {
  if (!fs.existsSync(LOG_FILE)) return [];
  const raw = fs.readFileSync(LOG_FILE, "utf8").trim();
  if (!raw) return [];
  return JSON.parse(raw);
}

function writeLog(logs) {
  fs.writeFileSync(LOG_FILE, JSON.stringify(logs, null, 2));
}

console.log("\n🗝️ Teacher Keyfree & Riche’s Secret Shopping Agent\n");

console.log("👧 Riche:");
console.log("“先生、今日のおつかいをお願いします！”\n");

console.log("🧑‍🏫 Teacher Keyfree:");
console.log("“わかりました。まずは情報屋さんに聞いてみます。”\n");

console.log("🧠 Nous / Teacher Keyfree is thinking...\n");

const plan = await thinkShoppingPlan();

if (plan.source === "nous") {
  console.log("✅ This shopping plan was generated by Nous API");
  console.log(`🤖 Nous model: `);
} else {
  console.log("🧸 This shopping plan was generated by mock fallback");
}
const paidInfo = await askPaidInfoShop(plan);

console.log("🏪 Paid Info Shop:");
console.log(paidInfo.shop);
console.log(`💸 ${paidInfo.message}\n`);

console.log("🧑‍🏫 Teacher Keyfree:");
console.log("“リチェの予算内です。支払います。”\n");

console.log("🐈 Sending payment on Tempo...\n");

const payment = await sendTempoPayment(plan.amount);

console.log("✅ Payment complete");
console.log(`amount: ${payment.amount} ${payment.token}`);
console.log(`tx: ${payment.txHash}\n`);

console.log("🛍️ Bought:");
console.log(plan.item + "\n");

console.log("🔒 Public reason:");
console.log(plan.publicReason + "\n");

console.log("🔒 True feeling:");
console.log("sealed in secret diary\n");

const entry = {
  createdAt: new Date().toISOString(),
  richeRequest: "先生、今日のおつかいをお願いします！",
  item: plan.item,
  category: plan.category,
  shop: plan.shop,
  publicReason: plan.publicReason,
  trueFeeling: plan.trueFeeling,
  payment
};

const logs = readLog();
logs.push(entry);
writeLog(logs);

console.log("📕 Saved to secret-log.json\n");
