import "dotenv/config";
import fs from "fs";
import { thinkShoppingPlan } from "./ai.js";
import { askPaidInfoShop } from "./mpp-client.js";
import { sendTempoPayment } from "./tempo.js";

const LOG_FILE = "./secret-log.json";

function readLog() {
  if (!fs.existsSync(LOG_FILE)) {
    return [];
  }

  const raw = fs.readFileSync(LOG_FILE, "utf8").trim();

  if (!raw) {
    return [];
  }

  try {
    return JSON.parse(raw);
  } catch (error) {
    console.log(
      "⚠️ secret-log.json の読み込みに失敗しました。新しい日誌を作ります。"
    );
    console.log(error.message);

    return [];
  }
}

function writeLog(logs) {
  fs.writeFileSync(
    LOG_FILE,
    JSON.stringify(logs, null, 2)
  );
}

function validatePaymentAmount(value) {
  const amount = Number(value);

  if (!Number.isFinite(amount)) {
    throw new Error(
      `送金額が正しい数値ではありません: ${value}`
    );
  }

  if (amount < 1 || amount > 5) {
    throw new Error(
      `送金額が許可範囲外です: ${amount} USDC`
    );
  }

  const rounded = Math.round(amount * 10) / 10;

  return rounded.toFixed(1);
}

async function main() {
  console.log(
    "\n🗝️ Teacher Keyfree & Riche’s Secret Shopping Agent\n"
  );

  console.log("👧 Riche:");
  console.log(
    "“先生、今日のおつかいをお願いします！”\n"
  );

  console.log("🧑‍🏫 Teacher Keyfree:");
  console.log(
    "“わかりました。何を買うか、いくら支払うか考えてみます。”\n"
  );

  console.log(
    "🧠 Nous / Teacher Keyfree is thinking...\n"
  );

  // Nousが買い物内容と金額を決める
  const plan = await thinkShoppingPlan();

  // 念のためshop.js側でも送金額を再検証
  plan.amount = validatePaymentAmount(plan.amount);

  if (plan.source === "nous") {
    console.log(
      "✅ This shopping plan was generated by Nous API"
    );
    console.log(
      `🤖 Nous model: ${
        plan.model ||
        process.env.NOUS_MODEL ||
        "unknown"
      }`
    );
  } else {
    console.log(
      "�� This shopping plan was generated by mock fallback"
    );
  }

  console.log(
    `💰 Teacher Keyfree decided: ${plan.amount} USDC`
  );
  console.log(
    `📝 Amount reason: ${plan.amountReason}\n`
  );

  const paidInfo = await askPaidInfoShop(plan);

  console.log("🏪 Paid Info Shop:");
  console.log(paidInfo.shop);
  console.log(`💸 ${paidInfo.message}\n`);

  console.log("🧑‍🏫 Teacher Keyfree:");
  console.log(
    `“この買い物には ${plan.amount} USDC がふさわしいでしょう。支払います。”\n`
  );

  console.log("🐈 Sending payment on Tempo...\n");

  // Nousが決めた金額をTempoで本当に送る
  const payment = await sendTempoPayment(plan.amount);

  console.log("✅ Payment complete");
  console.log(
    `amount: ${payment.amount} ${payment.token}`
  );
  console.log(`tx: ${payment.txHash}`);

  if (payment.blockNumber) {
    console.log(`block: ${payment.blockNumber}`);
  }

  console.log("");

  console.log("🛍️ Bought:");
  console.log(plan.item + "\n");

  console.log("🔒 Public reason:");
  console.log(plan.publicReason + "\n");

  console.log("🔒 True feeling:");
  console.log("sealed in secret diary\n");

  const entry = {
    createdAt: new Date().toISOString(),
    richeRequest:
      "先生、今日のおつかいをお願いします！",
    item: plan.item,
    category: plan.category,
    shop: plan.shop,
    publicReason: plan.publicReason,
    trueFeeling: plan.trueFeeling,
    amountReason: plan.amountReason,
    aiSource: plan.source || "unknown",
    aiModel:
      plan.model ||
      process.env.NOUS_MODEL ||
      "unknown",
    nousDecidedAmount: plan.amount,
    paidInfo,
    payment
  };

  const logs = readLog();
  logs.push(entry);
  writeLog(logs);

  console.log("📕 Saved to secret-log.json\n");
}

main().catch((error) => {
  console.error("\n❌ Shopping failed");
  console.error(error.message || error);

  process.exit(1);
});
